const data = [
  {
    contentHeading: "Templates",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Career and Technical Education",
    contentBoxes: [
      {
        contentType: "LESSON",
        contentTitle: "Self Management",
        nContent: "18 Slides",
        nPlays: "181 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Taco Recipe",
        nContent: "10 Questions",
        nPlays: "888 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Leadership Qualities",
        nContent: "10 Questions",
        nPlays: "212 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Email Etiquette and Anatomy",
        nContent: "10 Questions",
        nPlays: "1.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Plagiarism and Paraphrasing",
        nContent: "9 Questions",
        nPlays: "241 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Coping Strategies",
        nContent: "12 Slides",
        nPlays: "574 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Managing Conflict Summative",
        nContent: "20 Slides",
        nPlays: "8 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Budgeting Basics",
        nContent: "14 Slides",
        nPlays: "71 plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Mathematics",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "English and Language Arts",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "World Languages",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Science",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Computer Science and Skills",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Creative Arts",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Templates",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
  {
    contentHeading: "Templates",
    contentBoxes: [
      {
        contentType: "QUIZ",
        contentTitle: "Daily Check-in",
        nContent: "4 Questions",
        nPlays: "158.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Gratitude Lesson - SEL (Inspired by...",
        nContent: "10 Slides",
        nPlays: "15.6k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 6th Grade (with new question ...",
        nContent: "21 Questions",
        nPlays: "38.5k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 3rd Grade (with new question ...",
        nContent: "10 Questions",
        nPlays: "37.1k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Math: 8th Grade (with new question ...",
        nContent: "15 Questions",
        nPlays: "8.3k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "LESSON",
        contentTitle: "Science 101: The Universe (Inspired...",
        nContent: "19 Questions",
        nPlays: "1.9k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
      {
        contentType: "QUIZ",
        contentTitle: "Science: 6th Grade (with new questi...",
        nContent: "12 Questions",
        nPlays: "1.2k plays",
        contentImageUrl: "..\\assets\\media\\content-box-i1.png",
      },
    ],
  },
];

const quizQuestions = [
  {
    question: "What is the capital of India?",
    options: ["Mumbai", "Delhi", "Chennai", "Kolkata"],
    correctOption: 2,
  },
  {
    question: "What is 5 + 5?",
    options: ["25", "15", "20", "10"],
    correctOption: 4,
  },
  {
    question: "What is 10 - 5?",
    options: ["10", "5", "15", "20"],
    correctOption: 2,
  },
  {
    question: "What is 10 x 5?",
    options: ["20", "10", "50", "20"],
    correctOption: 3,
  },
  {
    question: "What is 10 / 5?",
    options: ["2", "10", "5", "15"],
    correctOption: 1,
  },
  {
    question: "What is 10 % 5?",
    options: ["2", "10", "5", "0"],
    correctOption: 4,
  },
];

const quizData_ = [
  {
    quizCode: "143236",
    quizTitle: "Sample Quiz 1",
    quizQuestions: [
      {
        question: "What is the capital of India?",
        options: ["Mumbai", "Delhi", "Chennai", "Kolkata"],
        correctOption: 2,
      },
      {
        question: "Who is the prime minister of India?",
        options: [
          "Pranab Mukharji",
          "Narendra Modi",
          "Amit Shah",
          "Pawan Kalyan",
        ],
        correctOption: 2,
      },
      {
        question: "Which social media platform was founded by Mark Zuckerberg?",
        options: ["Twitter", "Instagram", "Facebook", "LinkedIn"],
        correctOption: 3,
      },
      {
        question:
          "What does the acronym 'DM' commonly stand for in social media?",
        options: [
          "Direct Message",
          "Daily Mail",
          "Digital Media",
          "Data Management",
        ],
        correctOption: 1,
      },
      {
        question: "Which platform is known for its 280-character limit posts?",
        options: ["Facebook", "Instagram", "Twitter", "TikTok"],
        correctOption: 3,
      },
      {
        question: "What year was Instagram launched?",
        options: ["2008", "2010", "2012", "2014"],
        correctOption: 2,
      },
      {
        question:
          "Which social media platform is associated with professional networking?",
        options: ["Snapchat", "LinkedIn", "Pinterest", "WhatsApp"],
        correctOption: 2,
      },
    ],
  },
  {
    quizCode: "236236",
    quizTitle: "Sample Quiz 2",
    quizQuestions: [
      {
        question: "Which river is known as the 'Ganga of the South' in India?",
        options: ["Kaveri", "Godavari", "Krishna", "Narmada"],
        correctOption: 1,
      },
      {
        question: "Which Indian state is known as the 'Land of Five Rivers'?",
        options: ["Punjab", "Uttar Pradesh", "Bihar", "Haryana"],
        correctOption: 1,
      },
      {
        question: "Which is the easternmost state of India?",
        options: ["Assam", "Nagaland", "Manipur", "Arunachal Pradesh"],
        correctOption: 4,
      },
      {
        question:
          "Which Indian city is known as the 'Silicon Valley of India'?",
        options: ["Mumbai", "Hyderabad", "Bangalore", "Pune"],
        correctOption: 3,
      },
      {
        question: "Which is the largest state of India by area?",
        options: [
          "Madhya Pradesh",
          "Maharashtra",
          "Uttar Pradesh",
          "Rajasthan",
        ],
        correctOption: 4,
      },
      {
        question: "Which mountain range is located between India and Tibet?",
        options: [
          "Western Ghats",
          "Eastern Ghats",
          "Himalayas",
          "Vindhya Range",
        ],
        correctOption: 3,
      },
    ],
  },
  {
    quizCode: "071436",
    quizTitle: "Sample Quiz 3",
    quizQuestions: [
      {
        question: "What is the result of 7 x 8?",
        options: ["54", "56", "62", "64"],
        correctOption: 2,
      },
      {
        question: "If x + 5 = 12, what is the value of x?",
        options: ["5", "6", "7", "8"],
        correctOption: 3,
      },
      {
        question: "What is the square root of 144?",
        options: ["10", "11", "12", "13"],
        correctOption: 3,
      },
      {
        question: "What is 15% of 200?",
        options: ["20", "25", "30", "35"],
        correctOption: 3,
      },
      {
        question: "What is the next number in the sequence: 2, 4, 8, 16, ...?",
        options: ["24", "28", "30", "32"],
        correctOption: 4,
      },
      {
        question: "What is the area of a rectangle with length 8 and width 5?",
        options: ["35", "40", "45", "50"],
        correctOption: 2,
      },
    ],
  },
];

export const mainSectionData = data;
export const quizQuestionsData = quizQuestions;
export const quizData = quizData_;
